---
title: Terms of reference
date: 7 September 2023
description: >
  This document describes our official terms of reference as a working group of
  the European Society of Criminology.
---


## Name and Formation

The working group shall be known as the European Network for Open Criminology (ENOC). It shall be constituted on 6th September 2023 in Florence, Italy, and operate as a working group of the European Society of Criminology (ESC).



## Mission

ENOC brings together criminologists interested in open research and open science, aiming to become one of the driving forces for the promotion, training, application and rewarding of open research practices in criminology. This working group fosters and encourages all practices that embrace openness, integrity and reproducibility throughout the research cycle, including the collaborative working and sharing of research methodology, use and development of open access software, making analytic code and research equipment freely available online, and publishing research outputs (e.g., articles, books, data, peer reviews, software) in open access -- so anyone, from any part of the world, can view and download them without the need to log in or pay.

It is pressing for criminology to promote the open science principles. ‘Open criminology’ describes the set of practices that embrace openness, integrity and reproducibility throughout the cycle of researching the causes, consequences, prevention, control and treatment of crime and delinquency, offenders and victims, and the practice of criminal law, law enforcement, and judicial and correctional systems.



## Objectives

The primary objectives of ENOC are as follows:

- Establish a platform for networking, exchanging ideas, and developing joint projects and initiatives around open criminology.
- Foster collaboration and knowledge sharing among researchers, academics, practitioners, and policymakers in the field of open criminology.
- Promote and disseminate open science practices, transparency, and reproducibility within criminological research.
- Support the development and dissemination of innovative methodologies, tools, and technologies to support and enhance open criminology practices.
- Contribute to evidence-based policy-making by providing insights into the benefits and challenges of open approaches within the field of criminology.



## Activities

These goals of ENOC are reached through:

- Holding regular meetings of members and other interested researchers
- Coordinating “open criminology” sessions at Annual Meetings of the ESC
- Providing training on open criminology at Annual Meetings of the ESC and through other workshops and seminars
- Disseminating open research practices in criminology
- Establishing standards for openness in criminology
- Initiating and coordinating special issues on open criminology in criminology journals
- Establishing cross-national research ties and promoting international collaboration
- Partnering with stakeholders (e.g., practitioners, policy makers, journalists) who would benefit from improved and widespread open criminology practices



## Membership

The working group shall be open to all members of the European Society of Criminology (ESC) who have an interest in open criminology.

Membership shall be voluntary and free of charge.

Non-members of the ESC may participate in working group activities but will not have voting rights.

Membership status shall be reviewed annually, and inactive members may be removed from the group.



## Governance

The working group shall be led by a Steering Committee consisting of a Chair or up to three co-Chairs.

The Steering Committee members shall be elected by the working group members for a term of two years.

The Steering Committee shall be responsible for coordinating and facilitating the activities of the working group, organising meetings, and representing the working group within the ESC.

Decisions within the working group shall be made by a simple majority vote, with the Chair or co-Chair having a casting vote in the event of a tie.

The working group shall maintain regular communication with the ESC, providing updates on activities, achievements, and any financial matters as required.



## Meetings

The working group shall hold an annual meeting to discuss ongoing projects, plan future activities, and elect Steering Committee members (every other year).

Additional meetings, workshops, or webinars may be organized as deemed necessary by the working group members.

Meeting dates, venues, and agendas shall be communicated to the working group members well in advance.

Where possible, virtual participation shall be facilitated to ensure inclusivity and accessibility for members unable to attend in person.



## Resources

The working group shall rely on the voluntary contributions of its members.

The working group may seek external funding, sponsorships, or grants to support specific projects or initiatives.

Any funds obtained shall be managed in accordance with the financial policies and guidelines of the European Society of Criminology (ESC) or any other relevant funding source.

The working group shall maintain transparency and accountability in financial matters, providing regular reports on income, expenses, and the allocation of funds.

The working group may also utilize in-kind resources, such as shared research facilities, equipment, or technical expertise, as made available by participating members or institutions.



## Reporting and Evaluation

The working group shall submit an annual report to the European Society of Criminology (ESC) summarizing its activities, achievements, and future plans.

The report shall be made available to all working group members through email and other appropriate means.

The working group shall periodically evaluate its progress, effectiveness, and relevance to ensure its continued alignment with the objectives of the European Society of Criminology (ESC) and the evolving needs of its members.

Evaluation may involve surveys, feedback sessions, or other methods of gathering input from working group members and stakeholders.



## Amendments to the Terms of Reference

These Terms of Reference may be amended or revised by a two-thirds majority vote of the working group members.

Proposed amendments shall be communicated to the working group members at least 30 days before the voting takes place.

Amendments shall be submitted to the European Society of Criminology (ESC) for approval and inclusion in the official documentation.



## Dissolution

The working group may be dissolved by a two-thirds majority vote of the working group members.

In the event of dissolution, any remaining funds or assets shall be transferred to the European Society of Criminology (ESC) or another organization or institution determined by the working group members and approved by the ESC.
