---
title: "Presentation of ENOC in the Newsletter of the European Society of Criminology"
date: 2023-12-20
description: "Published in the Issue 21 of the ESC Newsletter"
---

**This is a copy of the article originally published in the [Issue 21 of the ESC Newsletter](https://escnewsletter.org/archive/working-group-reports-european-network-for-open-criminology-enoc)**

Over the past fifteen years, the social and behavioural sciences have navigated a *crisis of replicability*. Many landmark studies cannot be reproduced, and their findings cannot be replicated, leaving the credibility of many established research areas in doubt. This crisis has many causes, but much can be attributed to the way in which research is incentivised and practised within universities. The pressure to 'publish or perish', gain citations, or attract media attention has resulted in researchers deploying a range of questionable strategies that yield attractive results but may not accurately reflect the phenomena they studied. Criminology faced a large-scale crisis of replicability in 2020, when Justin Pickett reported significant anomalies in a set of publications from Eric Stewart, formerly a Professor at Florida State University. As a result, six articles were retracted, and one was corrected. Some of these articles had been published in flagship journals such as 'Criminology', 'Justice Quarterly', 'Social Problems', and 'Law & Society Review'.

An ever-growing group of researchers concerned with the crisis of replicability argue for the creation and development of new ways of working and new infrastructures that can, in part, restore the integrity of the social and behavioural sciences. These new ways of working affect every part of the research process - from the conception of ideas through to planning, data collection, analysis, and dissemination - but all have transparency and openness as guiding principles. Accordingly, this movement is known as 'open research', and it is increasingly an essential feature of high-quality research. If we are to ensure the future integrity of criminology, it is crucial that we accept the responsibility to *embrace open research principles and practices*.

In response to this challenge, 46 criminologists, based in 13 different countries, have founded the European Network for Open Criminology (ENOC). ENOC was launched as a working group of the European Society of Criminology in September 2023, in Florence, Italy. The newly created network will bring together European criminologists interested in Open Research, aiming to become one of the driving forces for the promotion, training, application, and rewarding of Open Research practices in criminology. ENOC fosters and encourages practices that embrace openness, integrity, and reproducibility throughout the research cycle. This includes the collaborative working and transparent sharing of research methodology (e.g., pre-registration), use and development of open access software, making analytic code and data freely available online, and publishing research outputs in open access - so anyone, from any part of the world, can view and download them without the need to log in or pay.

The primary goals of ENOC include sharing good practices in open research, raising awareness about the need for open criminology practices and development/training opportunities, and encouraging and promoting the use of open access repositories for academic publishing. ENOC also encourages and supports criminology journals to promote and reward open research practices and advocates for open research with funders, stakeholders, and research users.
